---
docker_install_docker_version: docker-ce=17.12.0~ce-0~ubuntu
docker_install_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_install_apt_key_sig: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
docker_install_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
